"""In-process port of TOUCAN's response-quality-check pipeline.

Wraps `step4.1_response_quality_check.py` (prompt construction) and
`step4.3_process_completion.py` (XML parsing + tool-call accuracy) so we can
run them on the trajectories generated by `run_toucan_agent_replay.py` without
shelling out to a separate vLLM job.

Inputs:
    - A list of generated trajectory records, each carrying the fields written
      by `evaluate_agent_replay`/`run_actual_mcp_execution_mode` when
      `record_replay_trajectories=True` (`messages`, `task_query`,
      `predicted_final_answer`, `target_tools`, ...).
    - A `LLM` instance (from `src.llm`) used as the judge model. Default is
      `gpt5-mini` to mirror TOUCAN's GPT-OSS-120B default while keeping latency
      low; pass `--judge-method` to override.

Output:
    - Per-task records augmented with `response_quality_assessment`
      (completeness, conciseness, tool-call accuracy) and per-mode aggregate
      scores (mean of completeness/conciseness, fraction with order_correct,
      mean desired_tools_used_percentage).
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any


TOUCAN_PROMPT_PATH = (
    Path.home()
    / "program"
    / "tools"
    / "Toucan"
    / "datagen"
    / "prompts"
    / "response_quality_check.md"
)


_RATING_TO_SCORE: dict[str, dict[str, int]] = {
    "completeness": {
        "very incomplete": 1,
        "incomplete": 2,
        "partially complete": 3,
        "mostly complete": 4,
        "fully complete": 5,
    },
    "conciseness": {
        "very redundant": 1,
        "redundant": 2,
        "average": 3,
        "concise": 4,
        "very concise": 5,
    },
}


def _load_prompt_template(template_path: Path) -> str:
    with template_path.open("r", encoding="utf-8") as handle:
        return handle.read()


def _to_toucan_messages(messages: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Translate OpenAI-style messages (with `tool_calls`/`role=tool`) into the
    TOUCAN function-call shape (`function_call`/`role=function`) so
    `condense_conversation` and `extract_tool_calls_sequence` operate on the
    same structure they would inside TOUCAN's pipeline.
    """
    converted: list[dict[str, Any]] = []
    pending_tool_call_names: list[str] = []
    for message in messages:
        role = message.get("role")
        if role == "assistant" and message.get("tool_calls"):
            for tool_call in message["tool_calls"]:
                fn = (tool_call or {}).get("function", {}) or {}
                name = fn.get("name") or "unknown"
                arguments = fn.get("arguments")
                converted.append(
                    {
                        "role": "assistant",
                        "function_call": {
                            "name": name,
                            "arguments": arguments,
                        },
                    }
                )
                pending_tool_call_names.append(name)
            continue
        if role == "tool":
            tool_name = message.get("name") or (
                pending_tool_call_names.pop(0) if pending_tool_call_names else "unknown"
            )
            converted.append(
                {
                    "role": "function",
                    "name": tool_name,
                    "content": message.get("content", ""),
                }
            )
            continue
        converted.append(message)
    return converted


def _condense_conversation(messages: list[dict[str, Any]]) -> str:
    """Mirror of `step4.1_response_quality_check.condense_conversation`."""
    lines: list[str] = []
    for msg in messages:
        role = msg.get("role", "")
        content = msg.get("content", "") or ""
        if role == "system":
            continue
        if role == "user":
            lines.append(f"User: {content}")
        elif role == "assistant":
            if "function_call" in msg:
                tool_name = (msg["function_call"] or {}).get("name", "unknown")
                lines.append(f"Assistant: [Called {tool_name}]")
            else:
                lines.append(f"Assistant: {content}")
        elif role == "function":
            tool_name = msg.get("name", "unknown")
            result_content = str(content)
            lines.append(f"Tool {tool_name}: {result_content[:100]} ... (truncated)")
    return "\n".join(lines)


def build_quality_check_prompt(
    *,
    template: str,
    question: str,
    target_tools: str,
    messages: list[dict[str, Any]],
) -> str:
    rendered = template
    rendered = rendered.replace("{QUESTION_CONTENT}", question)
    rendered = rendered.replace("{INTENDED_TOOL}", target_tools)
    rendered = rendered.replace("{CONVERSATION_HISTORY}", _condense_conversation(messages))
    return rendered


def _extract_xml(text: str, tag: str) -> str:
    pattern = rf"<{tag}>\s*<!\[CDATA\[(.*?)\]\]>\s*</{tag}>"
    match = re.search(pattern, text, re.DOTALL)
    if match:
        return match.group(1)
    pattern = rf"<{tag}>(.*?)</{tag}>"
    match = re.search(pattern, text, re.DOTALL)
    if match:
        return match.group(1)
    pattern = rf"<{tag}>\s*<!--.*?-->\s*(.*?)\s*</{tag}>"
    match = re.search(pattern, text, re.DOTALL)
    if match:
        return match.group(1)
    return ""


def _convert_rating(rating_text: str, dimension: str) -> int | None:
    if not rating_text:
        return None
    rating = rating_text.strip().lower()
    mapping = _RATING_TO_SCORE.get(dimension, {})
    if rating in mapping:
        return mapping[rating]
    for key, value in mapping.items():
        if key in rating or rating in key:
            return value
    try:
        score = int(rating)
    except ValueError:
        return None
    return score if 1 <= score <= 5 else None


def _parse_dimension(text: str, dimension: str) -> dict[str, Any] | None:
    block_match = re.search(rf"<{dimension}>(.*?)</{dimension}>", text, re.DOTALL)
    if not block_match:
        return None
    block = block_match.group(1)
    reasoning = _extract_xml(block, "reasoning").strip()
    rating = _extract_xml(block, "rating").strip().lower()
    score = _convert_rating(rating, dimension)
    if not reasoning or score is None:
        return None
    return {"reasoning": reasoning, "score": score}


def parse_quality_response(response_content: str) -> dict[str, Any] | None:
    if not response_content:
        return None
    block = re.search(r"<response>(.*?)</response>", response_content, re.DOTALL)
    body = block.group(1) if block else response_content
    completeness = _parse_dimension(body, "completeness")
    conciseness = _parse_dimension(body, "conciseness")
    if completeness is None or conciseness is None:
        return None
    overall = (completeness["score"] + conciseness["score"]) / 2.0
    return {
        "completeness": completeness,
        "conciseness": conciseness,
        "overall_score": overall,
    }


def _parse_target_tools(target_tools: Any) -> list[str]:
    if not target_tools:
        return []
    if isinstance(target_tools, list):
        items = target_tools
    elif isinstance(target_tools, str):
        items = [chunk.strip() for chunk in target_tools.split(",") if chunk.strip()]
    else:
        return []
    cleaned: list[str] = []
    for item in items:
        text = str(item).strip()
        if "::" in text:
            text = text.split("::", 1)[1].strip()
        if text:
            cleaned.append(text)
    return cleaned


def _extract_actual_tool_names(messages: list[dict[str, Any]]) -> list[str]:
    names: list[str] = []
    for message in messages:
        role = message.get("role")
        if role == "assistant" and message.get("function_call"):
            name = (message["function_call"] or {}).get("name") or ""
            if name:
                names.append(name)
        elif role == "assistant" and message.get("tool_calls"):
            for tool_call in message["tool_calls"]:
                fn = (tool_call or {}).get("function", {}) or {}
                name = fn.get("name") or ""
                if name:
                    names.append(name)
    return names


def compute_tool_call_accuracy(
    messages: list[dict[str, Any]],
    target_tools: Any,
) -> dict[str, Any]:
    """Mirror of `step4.3_process_completion.compute_tool_call_accuracy`."""
    targets = _parse_target_tools(target_tools)
    actuals = _extract_actual_tool_names(messages)

    if targets:
        used = sum(
            1 for target in targets if any(target in actual for actual in actuals)
        )
        desired_tools_used = used / len(targets)
    else:
        desired_tools_used = 1.0

    if len(targets) > 1 and len(actuals) >= len(targets):
        target_idx = 0
        for actual in actuals:
            if target_idx < len(targets) and targets[target_idx] in actual:
                target_idx += 1
        order_correct = target_idx >= len(targets)
    elif len(targets) <= 1:
        order_correct = True
    else:
        order_correct = False

    return {
        "desired_tools_used_percentage": desired_tools_used,
        "order_correctness": order_correct,
    }


def _format_target_tools_for_prompt(target_tools: Any) -> str:
    if isinstance(target_tools, list):
        return ", ".join(str(item) for item in target_tools)
    if target_tools is None:
        return ""
    return str(target_tools)


def evaluate_trajectory(
    *,
    judge_llm: Any,
    template: str,
    question: str,
    target_tools: Any,
    messages: list[dict[str, Any]],
    judge_temperature: float = 0.0,
) -> dict[str, Any]:
    toucan_messages = _to_toucan_messages(messages)
    prompt = build_quality_check_prompt(
        template=template,
        question=question or "",
        target_tools=_format_target_tools_for_prompt(target_tools),
        messages=toucan_messages,
    )
    judge_llm.system_prompt_enable = False
    judge_llm.system_prompt = None
    raw_response = judge_llm(prompt, None, temperature=judge_temperature)
    parsed = parse_quality_response(raw_response or "")
    accuracy = compute_tool_call_accuracy(toucan_messages, target_tools)
    return {
        "raw_response": raw_response,
        "parsed": parsed,
        "tool_call_accuracy": accuracy,
    }


def aggregate_mode_scores(
    judged_records: list[dict[str, Any]],
) -> dict[str, Any]:
    completeness_scores: list[int] = []
    conciseness_scores: list[int] = []
    overall_scores: list[float] = []
    desired_used: list[float] = []
    order_correct_flags: list[bool] = []
    parsed_count = 0

    for record in judged_records:
        parsed = (record.get("response_quality_assessment") or {}).get("parsed")
        if parsed:
            parsed_count += 1
            completeness_scores.append(parsed["completeness"]["score"])
            conciseness_scores.append(parsed["conciseness"]["score"])
            overall_scores.append(parsed["overall_score"])
        accuracy = (record.get("response_quality_assessment") or {}).get(
            "tool_call_accuracy"
        ) or {}
        if "desired_tools_used_percentage" in accuracy:
            desired_used.append(float(accuracy["desired_tools_used_percentage"]))
            order_correct_flags.append(bool(accuracy["order_correctness"]))

    def _mean(values: list[float]) -> float | None:
        return sum(values) / len(values) if values else None

    return {
        "evaluated_records": len(judged_records),
        "parsed_assessments": parsed_count,
        "average_completeness": _mean(completeness_scores),
        "average_conciseness": _mean(conciseness_scores),
        "average_overall": _mean(overall_scores),
        "average_desired_tools_used_percentage": _mean(desired_used),
        "order_correct_rate": (
            sum(order_correct_flags) / len(order_correct_flags)
            if order_correct_flags
            else None
        ),
    }


def load_prompt_template(template_path: Path = TOUCAN_PROMPT_PATH) -> str:
    return _load_prompt_template(template_path)
