#!/usr/bin/env python3
"""Generate the fixed crmarenapro test split (crmarena_100_test).

Design mirrors EnterpriseOps-Gym's opsgym_80_test:
- The TEST split is a fixed, committed list of task ids in
  green/tasks/task_ids.toml.
- TRAIN / VALID are *derived at load time* (green/crm/splits.py) from the
  remaining corpus: exclude test ids, order by sha256(str(idx)), first 10%
  -> valid, rest -> train. They are intentionally NOT stored here so the
  three sets can never drift apart.

The test list is exactly the sample the green agent draws for
`task_limit=100` (random.seed(42); random.sample(all_tasks, 100) over the
b2b corpus in dataset order), so it matches the already-recorded
Qwen3.6-27B baseline runs.

Idempotent: re-running rewrites the same file content.
"""

import json
import random
from pathlib import Path

HERE = Path(__file__).resolve().parent
TASKS_JSON = HERE / "green" / "data" / "crmarena_b2b_tasks.json"
OUT_TOML = HERE / "green" / "tasks" / "task_ids.toml"

TEST_SIZE = 100
SEED = 42


def main() -> None:
    tasks = json.loads(TASKS_JSON.read_text())
    ids = [row["idx"] for row in tasks]
    if len(set(ids)) != len(ids):
        raise SystemExit("duplicate idx values in corpus")

    # Reproduce the green agent's task_limit sampling exactly
    # (agent.py _get_tasks: random.seed(42); random.sample(all_tasks, limit)).
    random.seed(SEED)
    sampled = random.sample(tasks, TEST_SIZE)
    test_ids = [row["idx"] for row in sampled]

    OUT_TOML.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Fixed task-id splits for crmarenapro (b2b corpus, 2140 tasks).",
        "# Generated by assets/crmarenapro/make_splits.py — do not edit by hand.",
        "#",
        "# crmarena_100_test: fixed held-out test set. Identical to the seed-42",
        "# task_limit=100 sample used by the Qwen3.6-27B baseline runs.",
        "# crmarena_train / crmarena_valid are DERIVED at load time from the",
        "# remaining 2040 tasks (sha256-ordered, 10% valid / 90% train) — see",
        "# green/crm/splits.py. They are not listed here by design.",
        "",
        "crmarena_100_test = [",
    ]
    lines += [f"  {idx}," for idx in test_ids]
    lines += ["]", ""]
    OUT_TOML.write_text("\n".join(lines))
    print(f"wrote {OUT_TOML} with {len(test_ids)} test ids")


if __name__ == "__main__":
    main()
