"""Environment helpers for ready inference sessions."""

from __future__ import annotations

import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any


def normalize_sessions(started: object) -> dict[str, object]:
    """Normalize launcher output to a name -> session mapping."""

    if isinstance(started, Mapping):
        return {str(name): session for name, session in started.items()}
    name = str(getattr(started, "name", "default") or "default")
    return {name: started}


def default_session(sessions: Mapping[str, object]) -> object:
    """Return the default session, or the first session in sorted name order."""

    if "default" in sessions:
        return sessions["default"]
    if not sessions:
        raise ValueError("Inference config did not produce any sessions.")
    return sessions[sorted(sessions)[0]]


def generic_inference_env(sessions: Mapping[str, object]) -> dict[str, str]:
    """Return generic OpenAI-compatible and named endpoint env values."""

    values: dict[str, str] = {}
    for name, session in sorted(sessions.items()):
        prefix = _env_prefix(f"INFERENCE_{name}")
        api_base = _session_api_base(session)
        model = _session_model(session)
        api_key = _session_api_key(session)
        if api_base:
            values[f"{prefix}_BASE_URL"] = api_base
        if model:
            values[f"{prefix}_MODEL"] = model
        if api_key:
            values[f"{prefix}_API_KEY"] = api_key
        summary_path = _session_summary_path(session)
        if summary_path:
            values[f"{prefix}_LAUNCH_SUMMARY_PATH"] = summary_path

    selected = default_session(sessions)
    api_base = _session_api_base(selected)
    model = _session_model(selected)
    api_key = _session_api_key(selected)
    summary_path = _session_summary_path(selected)
    if api_base:
        values["OPENAI_BASE_URL"] = api_base
    if model:
        values["OPENAI_MODEL_NAME"] = model
    if api_key:
        values["OPENAI_API_KEY"] = api_key
    if summary_path:
        values["INFERENCE_LAUNCH_SUMMARY_PATH"] = summary_path
    return values


def write_env_file(path: str | Path, env: Mapping[str, str]) -> None:
    """Write shell exports for inference env values."""

    resolved_path = Path(path)
    resolved_path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["#!/usr/bin/env bash", "# Generated by remote-inference-launcher"]
    for name, value in sorted(env.items()):
        lines.append(f"export {name}={shell_quote(value)}")
    resolved_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def sessions_payload(sessions: Mapping[str, object]) -> dict[str, Any]:
    """Return a machine-readable payload for ready sessions."""

    endpoints: dict[str, dict[str, Any]] = {}
    for name, session in sorted(sessions.items()):
        endpoints[name] = {
            "api_base": _session_api_base(session),
            "model": str(getattr(session, "model", "") or ""),
            "served_model_name": str(getattr(session, "served_model_name", "") or ""),
            "api_key_set": bool(_session_api_key(session)),
            "local_port": getattr(session, "local_port", None),
            "remote_port": getattr(session, "remote_port", None),
            "backend_kind": str(getattr(session, "backend_kind", "") or ""),
            "run_id": str(getattr(session, "run_id", "") or ""),
            "summary_path": str(getattr(session, "summary_path", "") or ""),
            "cleanup_command": str(getattr(session, "cleanup_command", "") or ""),
            "logs": str(getattr(session, "logs", "") or getattr(session, "out_dir", "") or ""),
            "pid": getattr(session, "pid", None),
            "job_id": str(getattr(session, "job_id", "") or ""),
            "node": str(getattr(session, "node", "") or ""),
            "metadata": dict(getattr(session, "metadata", {}) or {}),
        }
    return {"endpoints": endpoints}


def bootstrap_result_payload(result: object) -> dict[str, Any]:
    """Return a machine-readable payload for vLLM bootstrap results."""

    manifest = dict(getattr(result, "manifest", {}) or {})
    return {
        "kind": str(getattr(result, "kind", "") or ""),
        "target": str(getattr(result, "target", "") or ""),
        "job_id": str(getattr(result, "job_id", "") or ""),
        "out_dir": str(getattr(result, "out_dir", "") or ""),
        "venv_path": str(manifest.get("venv_path", "") or ""),
        "python_bin": str(manifest.get("python_bin", "") or ""),
        "manifest_path": str(manifest.get("manifest_path", "") or ""),
        "manifest": manifest,
    }


def env_lines(env: Mapping[str, str]) -> list[str]:
    """Return deterministic KEY=value lines for CLI output."""

    return [f"{name}={value}" for name, value in sorted(env.items())]


def json_dumps(value: object) -> str:
    """Dump CLI payloads consistently."""

    return json.dumps(value, ensure_ascii=False, indent=2, default=str)


def shell_quote(value: str) -> str:
    """Return a POSIX shell single-quoted value."""

    return "'" + value.replace("'", "'\"'\"'") + "'"


def _session_api_base(session: object) -> str:
    return str(getattr(session, "api_base", "") or "").rstrip("/")


def _session_model(session: object) -> str:
    return str(getattr(session, "served_model_name", "") or getattr(session, "model", "") or "")


def _session_api_key(session: object) -> str:
    return str(getattr(session, "api_key", "") or "")


def _session_summary_path(session: object) -> str:
    return str(getattr(session, "summary_path", "") or "")


def _env_prefix(value: str) -> str:
    normalized = "".join(
        char.upper() if char.isascii() and char.isalnum() else "_" for char in value.strip()
    ).strip("_")
    if not normalized:
        raise ValueError("Environment prefix must contain at least one alphanumeric character.")
    return normalized
